### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by corbanmailloux** [corbanmailloux/Lift#2]

**Comment by corbanmailloux** [comment]
How about a web version, that can remain cross platform?

**Comment by edhaber** [comment]
Web version helps. But how does having only an android app make it cross platform?

**Comment by corbanmailloux** [comment]
What I meant is moving development to a web version and moving users to that instead of the Android version. Then there would be one common version.

**Comment by edhaber** [comment]
As long as it is an 'installable' web app where it behaves more like a real application than a website. Of course i don't think you can get a watch integration working from a web app. But you probably can get workout information from Jawbone's API

**Comment by corbanmailloux** [comment]
I developed a web version on the [gh-pages branch](https://github.com/corbanmailloux/Lift/tree/gh-pages) that, as soon as DNS updates, should be available at http://lift.corb.co. It should work as an "installable" web app, but @edhaber should let me know (I didn't test on iOS).

**Comment by edhaber** [comment]
Tested and works. It is keeping my streak as an "installed" web app
